# ── Puerto ──────────────────────────────────────
server.port=8085

# ── Oracle DB ───────────────────────────────────
spring.datasource.url=jdbc:oracle:thin:@//oracle-db:1521/XEPDB1
spring.datasource.username=pagos_user
spring.datasource.password=pagos_pass
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ── JPA / Hibernate ──────────────────────────────
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ── Nombre de la app ─────────────────────────────
spring.application.name=ms-pagos

app.ms-usuarios.url=http://ms-pedidos:8080/api/v1/pedidos
